### ISSUE TITLE
Handle call expired

### ISSUE THREAD

**Issue by dwilkie** [dwilkie/somleng#13]
```
[2016-11-02 05:18:07.568] ERROR CallController: <Adhearsion::Call::ExpiredError> This call is expired and is no longer accessible. See http://adhearsion.com/docs/calls for further details.
	/usr/src/app/vendor/bundle/ruby/2.3.0/bundler/gems/adhearsion-6db768c46752/lib/adhearsion/call.rb:24:in `rescue in method_missing'
	/usr/src/app/vendor/bundle/ruby/2.3.0/bundler/gems/adhearsion-6db768c46752/lib/adhearsion/call.rb:22:in `method_missing'
	/usr/src/app/vendor/bundle/ruby/2.3.0/bundler/gems/adhearsion-twilio-71779aca5e71/lib/adhearsion/twilio/controller_methods.rb:280:in `setup_twilio_call'
	/usr/src/app/vendor/bundle/ruby/2.3.0/bundler/gems/adhearsion-twilio-71779aca5e71/lib/adhearsion/twilio/controller_methods.rb:276:in `twilio_call'
	/usr/src/app/vendor/bundle/ruby/2.3.0/bundler/gems/adhearsion-twilio-71779aca5e71/lib/adhearsion/twilio/controller_methods.rb:61:in `notify_status_callback_url'
	/usr/src/app/vendor/bundle/ruby/2.3.0/bundler/gems/adhearsion-twilio-71779aca5e71/lib/adhearsion/twilio/controller_methods.rb:111:in `twilio_hangup'
	(eval):3:in `block in after'
	/usr/src/app/vendor/bundle/ruby/2.3.0/bundler/gems/adhearsion-6db768c46752/lib/adhearsion/call_controller.rb:196:in `instance_exec'
	/usr/src/app/vendor/bundle/ruby/2.3.0/bundler/gems/adhearsion-6db768c46752/lib/adhearsion/call_controller.rb:196:in `block (2 levels) in execute_callbacks'
	/usr/src/app/vendor/bundle/ruby/2.3.0/bundler/gems/adhearsion-6db768c46752/lib/adhearsion/foundation/exception_handler.rb:5:in `catching_standard_errors'
	/usr/src/app/vendor/bundle/ruby/2.3.0/bundler/gems/adhearsion-6db768c46752/lib/adhearsion/call_controller.rb:195:in `block in execute_callbacks'
	/usr/src/app/vendor/bundle/ruby/2.3.0/bundler/gems/adhearsion-6db768c46752/lib/adhearsion/call_controller.rb:194:in `each'
	/usr/src/app/vendor/bundle/ruby/2.3.0/bundler/gems/adhearsion-6db768c46752/lib/adhearsion/call_controller.rb:194:in `execute_callbacks'
	/usr/src/app/vendor/bundle/ruby/2.3.0/bundler/gems/adhearsion-6db768c46752/lib/adhearsion/call_controller.rb:203:in `after'
	/usr/src/app/vendor/bundle/ruby/2.3.0/bundler/gems/adhearsion-6db768c46752/lib/adhearsion/call_controller.rb:134:in `execute!'
	/usr/src/app/vendor/bundle/ruby/2.3.0/bundler/gems/adhearsion-6db768c46752/lib/adhearsion/call_controller.rb:102:in `block in exec'
	/usr/src/app/vendor/bundle/ruby/2.3.0/bundler/gems/adhearsion-6db768c46752/lib/adhearsion/call_controller.rb:101:in `catch'
	/usr/src/app/vendor/bundle/ruby/2.3.0/bundler/gems/adhearsion-6db768c46752/lib/adhearsion/call_controller.rb:101:in `exec'
	/usr/src/app/vendor/bundle/ruby/2.3.0/bundler/gems/adhearsion-6db768c46752/lib/adhearsion/call_controller.rb:118:in `exec_with_callback'
	/usr/src/app/vendor/bundle/ruby/2.3.0/bundler/gems/adhearsion-6db768c46752/lib/adhearsion/call_controller.rb:112:in `block (2 levels) in bg_exec'
	/usr/src/app/vendor/bundle/ruby/2.3.0/bundler/gems/adhearsion-6db768c46752/lib/adhearsion/foundation/exception_handler.rb:5:in `catching_standard_errors'
	/usr/src/app/vendor/bundle/ruby/2.3.0/bundler/gems/adhearsion-6db768c46752/lib/adhearsion/call_controller.rb:111:in `block in bg_exec'
	/usr/src/app/vendor/bundle/ruby/2.3.0/gems/celluloid-0.16.0/lib/celluloid/thread_handle.rb:13:in `block in initialize'
	/usr/src/app/vendor/bundle/ruby/2.3.0/gems/celluloid-0.16.0/lib/celluloid/actor_system.rb:32:in `block in get_thread'
	/usr/src/app/vendor/bundle/ruby/2.3.0/gems/celluloid-0.16.0/lib/celluloid/internal_pool.rb:130:in `block in create'
	/usr/src/app/vendor/bundle/ruby/2.3.0/gems/logging-2.1.0/lib/logging/diagnostic_context.rb:450:in `block in create_with_logging_context'
[2016-11-02 05:18:07.568] INFO  Adhearsion::Router::Route: Call af3f3df4-b3e3-4f70-a67d-8516e06c3ad8 routing completed. Call was already hung up.
```

**Comment by dwilkie** [comment]
Closed by #19
